package net.narusas.aceauction.pdf.gamjung;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
public class GamjungUI extends javax.swing.JFrame {

	// Variables declaration - do not modify
	public javax.swing.JButton insertButton;

	public javax.swing.JTextArea item1TextArea;

	public javax.swing.JTextArea item2TextArea;

	public javax.swing.JTextArea item3TextArea;
	public javax.swing.JTextArea item4TextArea;
	public javax.swing.JTextArea item5TextArea;
	public javax.swing.JButton nextTableButton;
	public javax.swing.JButton prevTableButton;
	public javax.swing.JLabel tableCountLabel;
	public javax.swing.JLabel tableNameLabel;
	// End of variables declaration
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private JTextField 시점;
	private JLabel jLabel6;
	private JTextField 기관;
	private JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JSeparator jSeparator1;
	/** Creates new form GamjungUI */
	public GamjungUI() {
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		tableNameLabel = new javax.swing.JLabel();
		prevTableButton = new javax.swing.JButton();
		nextTableButton = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		item1TextArea = new javax.swing.JTextArea();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		item2TextArea = new javax.swing.JTextArea();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		item3TextArea = new javax.swing.JTextArea();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		item4TextArea = new javax.swing.JTextArea();
		insertButton = new javax.swing.JButton();
		tableCountLabel = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jScrollPane5 = new javax.swing.JScrollPane();
		{
			jLabel6 = new JLabel();
			jLabel6.setText("\uc2dc\uc810");
		}
		{
			시점 = new JTextField();
		}
		item5TextArea = new javax.swing.JTextArea();

		tableNameLabel.setText("jLabel1");

		prevTableButton.setText("<<");

		nextTableButton.setText(">>");

		jLabel2.setText("1. \uc704\uce58,\uad50\ud1b5\uad00\ub828");

		item1TextArea.setColumns(20);
		item1TextArea.setRows(5);
		jScrollPane1.setViewportView(item1TextArea);

		jLabel3.setText("2. \uc774\uc6a9\uc0c1\ud0dc\uad00\ub828");

		item2TextArea.setColumns(20);
		item2TextArea.setRows(5);
		jScrollPane2.setViewportView(item2TextArea);

		jLabel4.setText("3. \ud1a0\uc9c0\uad00\ub828");

		item3TextArea.setColumns(20);
		item3TextArea.setRows(5);
		jScrollPane3.setViewportView(item3TextArea);

		jLabel5.setText("4. \ub3c4\ub85c\uad00\ub828");

		item4TextArea.setColumns(20);
		item4TextArea.setRows(5);
		jScrollPane4.setViewportView(item4TextArea);

		insertButton.setText("\uc785\ub825");

		tableCountLabel.setText("jLabel6");

		jLabel7.setText("5. \ub0c9\ub09c\ubc29 \uad00\ub828");
		{
			jLabel1 = new JLabel();
			jLabel1.setText("\uae30\uad00");
		}
		{
			기관 = new JTextField();
		}

		item5TextArea.setColumns(20);
		item5TextArea.setRows(5);
		jScrollPane5.setViewportView(item5TextArea);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setVerticalGroup(layout.createSequentialGroup()
			.addContainerGap()
			.addComponent(tableNameLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			    .addComponent(prevTableButton, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			    .addComponent(tableCountLabel, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			    .addComponent(nextTableButton, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			    .addComponent(insertButton, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE))
			.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			.addGroup(layout.createParallelGroup()
			    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
			        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
			        .addGap(21))
			    .addGroup(layout.createSequentialGroup()
			        .addGap(11)
			        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			            .addComponent(기관, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			            .addComponent(jLabel1, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
			            .addComponent(jLabel6, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			            .addComponent(시점, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE))))
			.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
			.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
			.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
			.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
			.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
			.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			.addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
			.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
			.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			.addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
			.addContainerGap());
		layout.setHorizontalGroup(layout.createSequentialGroup()
			.addContainerGap()
			.addGroup(layout.createParallelGroup()
			    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
			        .addGroup(layout.createParallelGroup()
			            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
			                .addGroup(layout.createParallelGroup()
			                    .addGroup(layout.createSequentialGroup()
			                        .addGroup(layout.createParallelGroup()
			                            .addComponent(jLabel1, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
			                            .addComponent(tableCountLabel, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE))
			                        .addGroup(layout.createParallelGroup()
			                            .addComponent(기관, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 204, GroupLayout.PREFERRED_SIZE)
			                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
			                                .addPreferredGap(기관, prevTableButton, LayoutStyle.ComponentPlacement.INDENT)
			                                .addComponent(prevTableButton, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			                                .addGap(162))))
			                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
			                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			                        .addGap(154))
			                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
			                        .addGroup(layout.createParallelGroup()
			                            .addComponent(jLabel3, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
			                                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			                                .addGap(24))
			                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
			                                .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			                                .addGap(24))
			                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
			                                .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			                                .addGap(8)))
			                        .addComponent(nextTableButton, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			                        .addGap(128)))
			                .addGap(0, 24, Short.MAX_VALUE)
			                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
			                .addComponent(시점, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE))
			            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
			                .addComponent(tableNameLabel, GroupLayout.PREFERRED_SIZE, 430, GroupLayout.PREFERRED_SIZE)
			                .addGap(33)))
			        .addComponent(insertButton, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			        .addGap(10))
			    .addComponent(jSeparator1, GroupLayout.Alignment.LEADING, 0, 511, Short.MAX_VALUE)
			    .addComponent(jScrollPane1, GroupLayout.Alignment.LEADING, 0, 511, Short.MAX_VALUE)
			    .addComponent(jScrollPane2, GroupLayout.Alignment.LEADING, 0, 511, Short.MAX_VALUE)
			    .addComponent(jScrollPane3, GroupLayout.Alignment.LEADING, 0, 511, Short.MAX_VALUE)
			    .addComponent(jScrollPane4, GroupLayout.Alignment.LEADING, 0, 511, Short.MAX_VALUE)
			    .addComponent(jScrollPane5, GroupLayout.Alignment.LEADING, 0, 511, Short.MAX_VALUE))
			.addGap(8));
		pack();
		this.setSize(539, 753);
	}// </editor-fold>
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GamjungUI().setVisible(true);
			}
		});
	}
	
	public JTextField get기관() {
		return 기관;
	}
	
	public JTextField get시점() {
		return 시점;
	}

}
