package net.narusas.aceauction.ui3;

public class UI3 extends javax.swing.JFrame {

	// Variables declaration - do not modify
	public javax.swing.JButton fileChooseButton;

	public javax.swing.JTextArea logTextArea;

	public javax.swing.JTextField ownersTextField;

	// End of variables declaration
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;

	/** Creates new form UI3 */
	public UI3() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		ownersTextField = new javax.swing.JTextField();
		fileChooseButton = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		logTextArea = new javax.swing.JTextArea();

		jPanel1.setLayout(new java.awt.BorderLayout());

		jPanel1.add(ownersTextField, java.awt.BorderLayout.CENTER);

		fileChooseButton.setText("Choose");
		jPanel1.add(fileChooseButton, java.awt.BorderLayout.EAST);

		jLabel1.setText("\uc18c\uc720\uc790");
		jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

		getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

		jPanel2.setLayout(new java.awt.BorderLayout());

		logTextArea.setColumns(20);
		logTextArea.setRows(5);
		jScrollPane1.setViewportView(logTextArea);

		jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UI3().setVisible(true);
			}
		});
	}

}